<?php
// session_start();

// if ($_SESSION['status'] != "Active") {
//     header("location:../Login/dist/login.php");
// }
$con = mysqli_connect('localhost', 'root', '', 'test4');
$sql = "SELECT bus_no FROM `bus_details`"; //for drop down
$bus_nos = mysqli_query($con, $sql);

$sql1 = "SELECT `Source` FROM `bus_details`"; //for drop down
$Source = mysqli_query($con, $sql1);

$sql2 = "SELECT `Destination` FROM `bus_details`"; //for drop down
$Destination = mysqli_query($con, $sql2);

$sql3 = "SELECT `Driver_emp_id` FROM `trip_incharge`"; //for drop down
$Driver_emp_id = mysqli_query($con, $sql3);

$sql4 = "SELECT `Conductor_emp_id` FROM `trip_incharge`"; //for drop down
$Conductor_emp_id = mysqli_query($con, $sql4);

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">

    <title>Conductor Trip Details</title>
</head>

<body id="grad" class="grad">
    <a class="button" href="../Login/dist/logout.php">Log Out</a>
    <a class="button" href="AdminDashboard.php">Go Back</a>
    <div class="maindiv" id="maindiv">

        <form align="center" action="SuperAdmin.php" method="post">
            <div class="title">

                <h2>Enter Trip Details</h2>
            </div>

            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->
                Bus Number: <select placeholder="Bus Number" name="BusNumber"><br><br>
                    <?php
                    // use a while loop to fetch data
                    // from the $all_categories variable
                    // and individually display as an option
                    while (
                        $bus_details = mysqli_fetch_array(
                            $bus_nos,
                        MYSQLI_ASSOC
                        )
                    ):
                        ;
                    ?>
                    <option value="<?php echo $bus_details["bus_no"];
                        // The value we usually set is the primary key
                    ?>">
                        <?php echo $bus_details["bus_no"];
                        // To show the category name to the user
                        ?>
                    </option>
                    <?php
                    endwhile;
                    // While loop must be terminated
                    ?>
                </select><br><br>






                Source: <select placeholder="Source" name="Source">
                    <?php
                    // use a while loop to fetch data
                    // from the $all_categories variable
                    // and individually display as an option
                    while (
                        $bus_details = mysqli_fetch_array(
                            $Source,
                        MYSQLI_ASSOC
                        )
                    ):
                        ;
                    ?>
                    <option value="<?php echo $bus_details["Source"];
                        // The value we usually set is the primary key
                    ?>">
                        <?php echo $bus_details["Source"];
                        // To show the category name to the user
                        ?>
                    </option>
                    <?php
                    endwhile;
                    // While loop must be terminated
                    ?>
                </select><br><br>



                Destination: <select placeholder="Destination" name="Destination">
                    <?php
                    // use a while loop to fetch data
                    // from the $all_categories variable
                    // and individually display as an option
                    while (
                        $bus_details = mysqli_fetch_array(
                            $Destination,
                        MYSQLI_ASSOC
                        )
                    ):
                        ;
                    ?>
                    <option value="<?php echo $bus_details["Destination"];
                        // The value we usually set is the primary key
                    ?>">
                        <?php echo $bus_details["Destination"];
                        // To show the category name to the user
                        ?>
                    </option>
                    <?php
                    endwhile;
                    // While loop must be terminated
                    ?>
                </select><br><br>





                Date: <input type="date" placeholder="Date" name="Date"><br><br>
                Scheduled Departure: <input type="time" placeholder="Destination" name="sdep"><br><br>
                Scheduled Arriival: <input type="time" placeholder="Date" name="sarr"><br><br>
                Driver ID: <select placeholder="Driver ID" name="did">
                    <?php
                    // use a while loop to fetch data
                    // from the $all_categories variable
                    // and individually display as an option
                    while (
                        $bus_details = mysqli_fetch_array(
                            $Driver_emp_id,
                        MYSQLI_ASSOC
                        )
                    ):
                        ;
                    ?>
                    <option value="<?php echo $bus_details["Driver_emp_id"];
                        // The value we usually set is the primary key
                    ?>">
                        <?php echo $bus_details["Driver_emp_id"];
                        // To show the category name to the user
                        ?>
                    </option>
                    <?php
                    endwhile;
                    // While loop must be terminated
                    ?>
                </select><br><br>




                ConductorID: <select placeholder="Conductor id" name="cid">
                    <?php
                    // use a while loop to fetch data
                    // from the $all_categories variable
                    // and individually display as an option
                    while (
                        $bus_details = mysqli_fetch_array(
                            $Conductor_emp_id,
                        MYSQLI_ASSOC
                        )
                    ):
                        ;
                    ?>
                    <option value="<?php echo $bus_details["Conductor_emp_id"];
                        // The value we usually set is the primary key
                    ?>">
                        <?php echo $bus_details["Conductor_emp_id"];
                        // To show the category name to the user
                        ?>
                    </option>
                    <?php
                    endwhile;
                    // While loop must be terminated
                    ?>
                </select><br><br>




            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script>
        $(function () {
            $(document).scroll(function () {
                var $nav = $("#mainNavbar");
                $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
            });
        });
    </script>
</body>

</html>