<?php
session_start();

if ($_SESSION['status'] != "Active") {
    header("location:../Login/dist/login.php");
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Conductor Trip Details</title>
    <link rel="icon" type="image/x-icon" href="../Images/favicon.ico">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="../Login/dist/style.css">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">
    <style>
        body {
            background: url("../Images/bg-dark.jpg") no-repeat center;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav id="mainNavbar" class="navbar navbar-light navbar-expand-md py-1 px-2 fixed-top"
        style="background-color: #0cb2f9;">
        <a class="navbar-brand" href="#">
            <img src="../Images/icon.png" width="45" height="35" class="d-inline-block align-middle" alt="">
            BUS MANAGEMENT SYSTEM
        </a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#navLinks" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navLinks">


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="AdminDashboard.php" class="nav-link">HOME</a>
                </li>
                <li class="nav-item">
                    <a href="../about.html" class="nav-link">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a href="../team.html" class="nav-link">TEAM</a>
                </li>


            </ul>
            <span class="nav-item ml-auto">
                <a class="nav-link" role="button" href="AdminDashboard.php">Go Back</a>
            </span>
            <span class="nav-item">
                <a class="nav-link" role="button" href="../Login/dist/logout.php">Logout</a>
            </span>


        </div>
    </nav>
    <div class="maindiv" id="maindiv" style="width: 40%;">

        <form action="SuperAdmin.php" method="post">
            <div class="title">

                <h2 class="text-center">Enter Trip Details</h2>
            </div>
            <br>
            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->

                <div class="form-group row">
                    <div class="col">
                        <label for="totalRevenue">Bus Number:</label>
                        <input class="form-control" input type="number" placeholder="Bus Number" name="BusNumber"
                            required>

                    </div>
                    <div class="col">
                        <label for="Date">Date: </label>
                        <input class="form-control" type="date" placeholder="Date" name="Date" required style="border-radius: 10px;
                    box-shadow: 5px 5px 5px #aaaaaa;">

                    </div>



                </div>
                <div class="form-group row">

                    <div class="col">
                        <label for="BusNumber">Source: </label>
                        <input class="form-control" type="text" placeholder="Source" name="Source" required>
                    </div>
                    <div class="col">
                        <label for="totalRevenue">Destination: </label>
                        <input class="form-control" type="text" placeholder="Destination" name="Destination" required>

                    </div>


                </div>

                <div class="form-group row">

                    <div class="col">
                        <label for="sdep">Scheduled Departure: </label>
                        <input class="form-control" type="time" placeholder="Destination" name="sdep" required>
                    </div>
                    <div class="col">
                        <label for="sarr">Scheduled Arrival: </label>
                        <input class="form-control" type="time" placeholder="Date" name="sarr" required>

                    </div>


                </div>

                <div class="form-group row">

                    <div class="col">
                        <label for="did">Driver ID: </label>
                        <input class="form-control" type="text" placeholder="Driver ID" name="did" required>
                    </div>
                    <div class="col">
                        <label for="cid">Conductor ID: </label>
                        <input class="form-control" type="text" placeholder="Conductor id" name="cid" required>

                    </div>


                </div>
            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script>
        $(function () {
            $(document).scroll(function () {
                var $nav = $("#mainNavbar");
                $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
            });
        });
    </script>
</body>

</html>