<?php
session_start();

if ($_SESSION['status'] != "Active") {
    header("location:../Login/dist/login.php");
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">

    <title>Conductor Trip Details</title>
</head>

<body id="grad" class="grad">
    <a class="button" href="../Login/dist/logout.php">Log Out</a>
    <a class="button" href="AdminDashboard.php">Go Back</a>
    <div class="maindiv" id="maindiv">

        <form align="center" action="SuperAdmin.php" method="post">
            <div class="title">

                <h2>Enter Trip Details</h2>
            </div>

            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->
                Bus Number: <input type="number" placeholder="Bus Number" name="BusNumber" required><br><br>
                Source: <input type="text" placeholder="Source" name="Source" required><br><br>
                Destination: <input type="text" placeholder="Destination" name="Destination" required><br><br>
                Date: <input type="date" placeholder="Date" name="Date" required><br><br>
                Scheduled Departure: <input type="time" placeholder="Destination" name="sdep" required><br><br>
                Scheduled Arriival: <input type="time" placeholder="Date" name="sarr" required><br><br>
                Driver ID: <input type="text" placeholder="Driver ID" name="did" required><br><br>
                ConductorID: <input type="text" placeholder="Conductor id" name="cid" required><br><br>


            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>