<?php

// database connection code
// $con = mysqli_connect('localhost', 'database_user', 'database_password','database');

$con = mysqli_connect('localhost', 'root', '', 'test4');

// get the post records
$BusNumber = $_POST['BusNumber'];
$Source = $_POST['Source'];
$Destination = $_POST['Destination'];
$Date = $_POST['Date'];
//trip_incharge_post_combine
$did = $_POST['did'];
$cid = $_POST['cid'];
$sdep = $_POST['sdep'];
$sarr = $_POST['sarr'];





//generating trip id
$query = "SELECT MAX(`trip_no`) AS LASTTRIP  FROM `bus_details`;";

$result = mysqli_query($con, $query);
if ($result->num_rows > 0) {
    // OUTPUT DATA OF EACH ROW
    while ($row = $result->fetch_assoc()) {
        $tripNO = $row['LASTTRIP'];
        $tripNO++;
    }
}





// database insert SQL code

$sqli = "INSERT INTO `Bus_details`(`trip_no`,`bus_no`, `Source`, `Destination`,`TripDate`) 
  VALUES('$tripNO', '$BusNumber', '$Source','$Destination','$Date')";

// insert in database 
$rs = mysqli_query($con, $sqli);
// database insert SQL code
//trip-incharge details query running simulatenouslly
$sql = "INSERT INTO `trip_incharge`(`trip_no_incharge`,`Driver_emp_id`, `Conductor_emp_id`, `scheduled_dept_time`,`scheduled_arr_time`) 
  VALUES('$tripNO', '$did', '$cid','$sdep','$sarr')";

// insert in database 
$rs = mysqli_query($con, $sql);

//echo "<script>alert("Recorded successfully. Your trip Number is";)</script>";
echo "Trip number generated Successfully. Trip Number is '{$tripNO}'"; //DIsplay properly

?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="tripDetails.css">

    <title>Conductor Trip Details</title>
</head>

<body id="grad" class="grad">
    <a class="button" href="../Login/dist/logout.php">Log Out</a>
    <a class="button" href="AdminDashboard.php">Go Back</a>
    <div class="maindiv" id="maindiv">

        <form align="center" action="" method="post">
            <div class="title">

                <h2>Enter Trip Details</h2>
            </div>

            <div class="info">

                <!-- Trip Number: <input type="number" placeholder="Trip Number" name="TripNumber"><br><br> ..this is being autogenerated -->
                Bus Number: <input type="number" placeholder="Bus Number" name="BusNumber" required><br><br>
                Source: <input type="text" placeholder="Source" name="Source" required><br><br>
                Destination: <input type="text" placeholder="Destination" name="Destination" required><br><br>
                Date: <input type="date" placeholder="Date" name="Date" required><br><br>
                Scheduled Departure: <input type="time" placeholder="Destination" name="sdep" required><br><br>
                Scheduled Arriival: <input type="time" placeholder="Date" name="sarr" required><br><br>
                Driver ID: <input type="text" placeholder="Driver ID" name="did" required><br><br>
                ConductorID: <input type="text" placeholder="Conductor id" name="cid" required><br><br>


            </div>

            <br>

            <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>